### ISSUE TITLE
是配置的问题？还是电信干扰的问题？还是在linode上限制使用KCP？如何更好降低延迟？

### ISSUE THREAD

**Issue by wulongji2016** [xtaci/kcptun#344]
测试了很多次，在Ubuntu16版的linode的VPS上。
在VPS上，netstat –apn | grep 554 发现好像端口没有打开，命令没有返回任何结果。（不是十分熟悉Ubuntu）
在自己客户端上 telnet 554 连接不上，连ss的8888端口可以连上。
求大神指点：
1）是配置的问题？还是电信劫持和干扰的问题？还是Ubuntu在linode上限制使用KCP？
2）KCP对视频强占宽带效果应该比较明显。但是对对于降低延迟是否明显？我主要经常使用俄罗斯邮箱，直连延迟很高400-500ms之间，经常卡的无法打开邮箱，借助SS+KCP是否能启到降低延迟的作用？ 效果是否明显？最好能ping值控制在200-250ms之间比较流畅一点。
3）电信和移动，以及联通，那个的出口宽带不拥堵，更低延迟？
我发现以前用的移动宽带的直连俄罗斯邮箱基本不卡，现在的电信卡的很。差别很大。不知道联通的如何？

客户端输出日志：

2016/12/20 19:37:44 version: 20161202
2016/12/20 19:37:44 listening on: [::]:12948
2016/12/20 19:37:44 encryption: aes
2016/12/20 19:37:44 nodelay parameters: 1 20 2 1
2016/12/20 19:37:44 remote address: 178.79.129.---:554
2016/12/20 19:37:44 sndwnd: 128 rcvwnd: 1024
2016/12/20 19:37:44 compression: true
2016/12/20 19:37:44 mtu: 1350
2016/12/20 19:37:44 datashard: 10 parityshard: 3
2016/12/20 19:37:44 acknodelay: false
2016/12/20 19:37:44 dscp: 0
2016/12/20 19:37:44 sockbuf: 4194304
2016/12/20 19:37:44 keepalive: 10
2016/12/20 19:37:44 conn: 1
2016/12/20 19:37:44 autoexpire: 0
2016/12/20 19:38:17 stream opened
2016/12/20 19:38:17 stream closed

服务端输出的日志：
2016/12/20 18:16:32 version: 20161202
2016/12/20 18:16:32 listen udp :554: bind: address already in use
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
	/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:311
github.com/urfave/cli.HandleAction
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483
github.com/urfave/cli.(*App).Run
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254
main.main
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:355
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2184

json 方式加载的配置，输出结果：
github.com/xtaci/kcp-go.ListenWithOptions
	/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:311
github.com/urfave/cli.HandleAction
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483
github.com/urfave/cli.(*App).Run
	/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254
main.main
	/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:355
runtime.main
	/usr/local/go/src/runtime/proc.go:185
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2184
2016/12/20 19:44:34 version: 20161202
2016/12/20 19:44:34 listening on: 178.79.129.---:8080
2016/12/20 19:44:34 target: 127.0.0.1:8888
2016/12/20 19:44:34 encryption: aes
2016/12/20 19:44:34 nodelay parameters: 1 20 2 1
2016/12/20 19:44:34 sndwnd: 1024 rcvwnd: 1024
2016/12/20 19:44:34 compression: true
2016/12/20 19:44:34 mtu: 1350
2016/12/20 19:44:34 datashard: 10 parityshard: 3
2016/12/20 19:44:34 acknodelay: false
2016/12/20 19:44:34 dscp: 0
2016/12/20 19:44:34 sockbuf: 4194304
2016/12/20 19:44:34 keepalive: 10
2016/12/20 19:45:26 remote address: 123.166.67.---:27142
2016/12/20 19:45:26 dial tcp 127.0.0.1:8888: getsockopt: connection refused
2016/12/20 19:45:26 dial tcp 127.0.0.1:8888: getsockopt: connection refused
2016/12/20 19:45:27 dial tcp 127.0.0.1:8888: getsockopt: connection refused

**Comment by guliujian** [comment]
上面写着address already in use，端口被占用了，看看什么程序占用的，要么关掉要么换端口

On Dec 21, 2016 3:55 PM, "wulongji2016" <notifications@github.com> wrote:

测试了很多次，在Ubuntu16版的linode的VPS上。
在VPS上，netstat –apn | grep 554 发现好像端口没有打开，命令没有返回任何结果。（不是十分熟悉Ubuntu）
在自己客户端上 telnet 554 连接不上，连ss的8888端口可以连上。
求大神指点：
1）是配置的问题？还是电信劫持和干扰的问题？还是Ubuntu在linode上限制使用KCP？
2）KCP对视频强占宽带效果应该比较明显。但是对对于降低延迟是否明显？我主要经常使用俄罗斯邮箱，
直连延迟很高400-500ms之间，经常卡的无法打开邮箱，借助SS+KCP是否能启到降低延迟的作用？ 效果是否明显？最好能ping值控制在200-
250ms之间比较流畅一点。
3）电信和移动，以及联通，那个的出口宽带不拥堵，更低延迟？
我发现以前用的移动宽带的直连俄罗斯邮箱基本不卡，现在的电信卡的很。差别很大。不知道联通的如何？

客户端输出日志：

2016/12/20 19:37:44 version: 20161202
2016/12/20 19:37:44 listening on: [::]:12948
2016/12/20 19:37:44 encryption: aes
2016/12/20 19:37:44 nodelay parameters: 1 20 2 1
2016/12/20 19:37:44 remote address: 178.79.129.---:554
2016/12/20 19:37:44 sndwnd: 128 rcvwnd: 1024
2016/12/20 19:37:44 compression: true
2016/12/20 19:37:44 mtu: 1350
2016/12/20 19:37:44 datashard: 10 parityshard: 3
2016/12/20 19:37:44 acknodelay: false
2016/12/20 19:37:44 dscp: 0
2016/12/20 19:37:44 sockbuf: 4194304
2016/12/20 19:37:44 keepalive: 10
2016/12/20 19:37:44 conn: 1
2016/12/20 19:37:44 autoexpire: 0
2016/12/20 19:38:17 stream opened
2016/12/20 19:38:17 stream closed

服务端输出的日志：
2016/12/20 18:16:32 version: 20161202
2016/12/20 18:16:32 listen udp :554: bind: address already in use
net.ListenUDP
github.com/xtaci/kcp-go.ListenWithOptions
/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:311
github.com/urfave/cli.HandleAction
/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483
github.com/urfave/cli.(*App).Run
/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254
main.main
/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:355
runtime.main
/usr/local/go/src/runtime/proc.go:185
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:2184

json 方式加载的配置，输出结果：
github.com/xtaci/kcp-go.ListenWithOptions
/Users/xtaci/.godeps/src/github.com/xtaci/kcp-go/sess.go:856
main.main.func1
/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:311
github.com/urfave/cli.HandleAction
/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:483
github.com/urfave/cli.(*App).Run
/Users/xtaci/.godeps/src/github.com/urfave/cli/app.go:254
main.main
/Users/xtaci/.godeps/src/github.com/xtaci/kcptun/server/main.go:355
runtime.main
/usr/local/go/src/runtime/proc.go:185
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:2184
2016/12/20 19:44:34 version: 20161202
2016/12/20 19:44:34 listening on: 178.79.129.---:8080
2016/12/20 19:44:34 target: 127.0.0.1:8888
2016/12/20 19:44:34 encryption: aes
2016/12/20 19:44:34 nodelay parameters: 1 20 2 1
2016/12/20 19:44:34 sndwnd: 1024 rcvwnd: 1024
2016/12/20 19:44:34 compression: true
2016/12/20 19:44:34 mtu: 1350
2016/12/20 19:44:34 datashard: 10 parityshard: 3
2016/12/20 19:44:34 acknodelay: false
2016/12/20 19:44:34 dscp: 0
2016/12/20 19:44:34 sockbuf: 4194304
2016/12/20 19:44:34 keepalive: 10
2016/12/20 19:45:26 remote address: 123.166.67.---:27142
2016/12/20 19:45:26 dial tcp 127.0.0.1:8888: getsockopt: connection refused
2016/12/20 19:45:26 dial tcp 127.0.0.1:8888: getsockopt: connection refused
2016/12/20 19:45:27 dial tcp 127.0.0.1:8888: getsockopt: connection refused

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xtaci/kcptun/issues/344>, or mute the thread

**Comment by baggiogogo** [comment]
联通的话在我这，广州出口较稳定，北京次之，不要选上海。VPS选靠谱商家洛杉矶QN机房就好，不用亚洲优化（电信选亚洲优化效果好），但有个隐形的问题，可能有些地区出口带宽会限制。
移动的话，应该是可以的，但也有个问题，无外网IP，如果做跳板，需要配置内网穿透等等。
最终，能实际试试是最稳妥的。

**Comment by wulongji2016** [comment]
这次端口没有被占用，但是无法连接，免费大神看一下，我英语不好。很差。
2016/12/20 19:53:55 broken pipe
2016/12/20 19:54:21 broken pipe
最新的如下：
2016/12/21 11:17:04 version: 20161202
2016/12/21 11:17:04 listening on: 178.79.129.---:9898
2016/12/21 11:17:04 target: 127.0.0.1:8888
2016/12/21 11:17:04 encryption: aes
2016/12/21 11:17:04 nodelay parameters: 1 20 2 1
2016/12/21 11:17:04 sndwnd: 1024 rcvwnd: 1024
2016/12/21 11:17:04 compression: true
2016/12/21 11:17:04 mtu: 1350
2016/12/21 11:17:04 datashard: 10 parityshard: 3
2016/12/21 11:17:04 acknodelay: false
2016/12/21 11:17:04 dscp: 0
2016/12/21 11:17:04 sockbuf: 4194304
2016/12/21 11:17:04 keepalive: 10
2016/12/21 11:24:44 remote address: 123.166.94.151:28005
2016/12/21 11:24:44 dial tcp 127.0.0.1:8888: getsockopt: connection refused
2016/12/21 11:24:45 dial tcp 127.0.0.1:8888: getsockopt: connection refused
2016/12/21 11:24:45 dial tcp 127.0.0.1:8888: getsockopt: connection refused
客户端：
2016/12/21 11:24:52 version: 20161202
2016/12/21 11:24:52 listening on: [::]:12948
2016/12/21 11:24:52 encryption: aes
2016/12/21 11:24:52 nodelay parameters: 1 20 2 1
2016/12/21 11:24:52 remote address: 178.79.129.---:9898
2016/12/21 11:24:52 sndwnd: 128 rcvwnd: 1024
2016/12/21 11:24:52 compression: true
2016/12/21 11:24:52 mtu: 1350
2016/12/21 11:24:52 datashard: 10 parityshard: 3
2016/12/21 11:24:52 acknodelay: false
2016/12/21 11:24:52 dscp: 0
2016/12/21 11:24:52 sockbuf: 4194304
2016/12/21 11:24:52 keepalive: 10
2016/12/21 11:24:52 conn: 1
2016/12/21 11:24:52 autoexpire: 0
2016/12/21 11:24:52 stream opened
2016/12/21 11:24:52 stream opened
2016/12/21 11:24:54 stream opened
2016/12/21 11:24:54 stream opened
2016/12/21 11:24:55 stream closed
2016/12/21 11:24:55 stream closed

**Comment by guliujian** [comment]
免费大神什么鬼，还有你的ss是监听在0.0.0.0还是监听在你公网ip的你netstat -anp|grep 8888看一下

**Comment by wulongji2016** [comment]
@guliujian 
root@hostWLJ:~# netstat -anp|grep 8888
tcp        0      0 178.79.129.---:8888     0.0.0.0:*               LISTEN      12520/python
udp        0      0 178.79.129.---:8888     0.0.0.0:*                           12520/python

**Comment by guliujian** [comment]
你监听了公网地址上你如果只用kcptun的话就把ss server监听127.0.0.1如果都用的话ssserver监听0.0.0.0

On Dec 21, 2016 5:02 PM, "wulongji2016" <notifications@github.com> wrote:

@guliujian <https://github.com/guliujian>
root@hostWLJ:~# netstat -anp|grep 8888
tcp 0 0 178.79.129.---:8888 0.0.0.0:* LISTEN 12520/python
udp 0 0 178.79.129.---:8888 0.0.0.0:* 12520/python

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/xtaci/kcptun/issues/344#issuecomment-268471380>, or mute
the thread

**Comment by dearneo** [comment]
给楼上免费大神点个赞，楼主的问题应该就是这个原因

**Comment by wulongji2016** [comment]
如果想KCP 配合SS一起使用，配置如下？ 我修改配置了， 但是服务器输出日志还是有问题，见下面
{
    "server":"178.79.129.---",
    "server_port":8888,
    "local_address": "0.0.0.0",
    "local_port":1080,
    "password":"---",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}

2016/12/21 12:44:54 version: 20161202
2016/12/21 12:44:54 listening on: 178.79.129.171:9898
2016/12/21 12:44:54 target: 127.0.0.1:8888
2016/12/21 12:44:54 encryption: aes
2016/12/21 12:44:54 nodelay parameters: 1 20 2 1
2016/12/21 12:44:54 sndwnd: 1024 rcvwnd: 1024
2016/12/21 12:44:54 compression: true
2016/12/21 12:44:54 mtu: 1350
2016/12/21 12:44:54 datashard: 10 parityshard: 3
2016/12/21 12:44:54 acknodelay: false
2016/12/21 12:44:54 dscp: 0
2016/12/21 12:44:54 sockbuf: 4194304
2016/12/21 12:44:54 keepalive: 10
2016/12/21 12:44:54 remote address: 123.166.94.151:28067
2016/12/21 12:45:24 broken pipe
2016/12/21 12:45:25 remote address: 123.166.94.151:28067
2016/12/21 12:45:55 broken pipe

客户端日志：
2016/12/21 11:46:02 stream opened
2016/12/21 11:46:16 stream opened
2016/12/21 11:46:22 session scavenged
2016/12/21 11:46:32 stream closed
2016/12/21 11:46:32 stream closed

**Comment by guliujian** [comment]
server改成0.0.0.0而不是localaddress

**Comment by wulongji2016** [comment]
客户端输出日志：
2016/12/21 14:10:56 version: 20161202
2016/12/21 14:10:57 listening on: [::]:12948
2016/12/21 14:10:57 encryption: aes
2016/12/21 14:10:57 nodelay parameters: 1 20 2 1
2016/12/21 14:10:57 remote address: 178.79.129.---:9898
2016/12/21 14:10:57 sndwnd: 128 rcvwnd: 1024
2016/12/21 14:10:57 compression: true
2016/12/21 14:10:57 mtu: 1350
2016/12/21 14:10:57 datashard: 10 parityshard: 3
2016/12/21 14:10:57 acknodelay: false
2016/12/21 14:10:57 dscp: 0
2016/12/21 14:10:57 sockbuf: 4194304
2016/12/21 14:10:57 keepalive: 10
2016/12/21 14:10:57 conn: 1
2016/12/21 14:10:57 autoexpire: 0
2016/12/21 14:11:24 stream opened
2016/12/21 14:11:27 stream closed
2016/12/21 14:11:27 stream opened

**Comment by wulongji2016** [comment]
出现了新问题，SSH 登陆服务器，被干扰了，晚上经常掉线了。

**Comment by wulongji2016** [comment]
另外，如果KCP 单独使用，如何配置？  我目前想加速登陆俄罗斯的邮箱yandex.ru，降低延迟。
（如果可以，日后在配合SS翻墙，）

**Comment by dearneo** [comment]
楼上，如果使用邮箱客户端的话，直接在客户端里指定网络代理为kcptun加速后的ss即可，不需要另外配置。

**Comment by wulongji2016** [comment]
这是8888SS服务器端口情况 ，我正确设置了？ 打算KCP和SS配合使用。
tcp        0      0 0.0.0.0:8888            0.0.0.0:*               LISTEN                               13881/python
tcp        0      0 178.79.129.171:8888     123.166.69.182:28127    TIME_WAIT                            -
tcp        0      0 178.79.129.171:8888     123.166.69.182:28159    ESTABLISHED                          13881/python
tcp        0      0 178.79.129.171:8888     123.166.69.182:28235    ESTABLISHED                          13881/python
udp        0      0 0.0.0.0:8888            0.0.0.0:*                                                    13881/python

**Comment by wulongji2016** [comment]
server改成0.0.0.0而不是localaddress  修改之后，重启了两次服务端，可以使用了，十分感谢！！！

**Comment by wulongji2016** [comment]
`
![2016-12-22-1](https://cloud.githubusercontent.com/assets/24681808/21414733/23fb66f2-c813-11e6-978a-7e834898746a.jpg)
![2016-12-22-2](https://cloud.githubusercontent.com/assets/24681808/21414734/23fce7f2-c813-11e6-8bd9-1930e8683c23.jpg)

`

**Comment by wulongji2016** [comment]
使用了大约30分钟，断流了。请问是不是电信干扰了啊？  黑龙江电信

**Comment by bettermanbao** [comment]
https://github.com/xtaci/kcptun/issues/353
