### ISSUE TITLE
Please add support for udp

### ISSUE THREAD

**Issue by lightpencil** [xtaci/kcptun#458]
### Please add support for udp.
As xtaci said there's no plan for udp support as we could "always find a workaround for it". However, it doesn't apply for all conditions, and adding udp support will simplify a lot of "workaround", especially on windows servers, so that there would be no need for other softwares etc.

Thanks a lot.

**Comment by wangyu-** [comment]
udp加速方案。可以配合kcptun一起使用，达到同时加速tcp和udp的目的。
https://github.com/wangyu-/UDPspeeder

**Comment by viniciusmr** [comment]
> udp加速方案。可以配合kcptun一起使用，达到同时加速tcp和udp的目的。
> https://github.com/wangyu-/UDPspeeder
> ![capture3](https://user-images.githubusercontent.com/4922024/29179889-d367c430-7daa-11e7-9973-42c9f1edd75f.PNG)

While UDPspeeder it's a great idea, and directly address the requirement, I would argue still for an option to run kcptun over UDP. 

If not for the fact that _diversity in software is good and healthy_, then maybe because UDPspeeder seems to have it's own limitations when dealing with high latency and high throughput. =/
While kcptun seemed to be much less affected by adverse (bad) network conditions in my testing.

**Comment by ttimasdf** [comment]
> Ultimately, however, I tried kcptun and after a couple of hours of tweaking, managed to achieve much higher transfers speeds using it than UDPspeeder. I'm talking about ~90 Mbps vs ~10 Mbps.

@viniciusmr could you please post your test scenario so we could (possibly) reproduce it? The tunneled traffic is with TCP or UDP?

I'll post my result here as well (if I still remember this afterwards 😅 ).
