### ISSUE TITLE
kcptun CPU load optimization

### ISSUE THREAD

**Issue by PtDragon** [xtaci/kcptun#529]
At high speeds ther is a problem with CPU load.
I don't know where exactly it is, surely not in encryption and not in compression parts(because disabling both makes nearly no difference).
For example 2 cores at 3.4Ghz can pass just around 180-200mbit of traffic(here i take uncpmpressable traffic like https, mp4 and so on) thru kcptun(using 2 or more kcptun instances).
Is there a way to significantly boost the processing speed?
I do have VPS with great bandwidth(10Gbit) but small enough CPU resources(2 cores at 3.4Ghz).
Current settings: ./server_linux_amd64 -l :3771 -t 127.0.0.1:3128 --key $key --crypt aes-256 --mode manual -nodelay 1 -interval 20 -resend 1 -nc 1 --sndwnd 4096 --rcvwnd 4096 --datashard 8 --parityshard 1

**Comment by xxxman2008** [comment]
encrypt  and "packet proceed"  rely on CPU .  And VPS is not an good test environment.   you share resources with others. Event  in real world , PC is not  good for  "network packet proceed".  that's why we usually use "hardware switch/router".

Talking about 10G network ,there's lots of things to do for optimize .  So.....i think you've got acceptable result.

**Comment by PtDragon** [comment]
@xxxman2008 
VPS is good enough for testing(as i do minimum 3 tests at different time and average results then).
Also this is software solution that surely can be optimized(as there is bottleneck for sure).
Same VPS easily handles over gigabit of stunnel traffic so it is not about software/hardware processing, it is about optimizing software.

**Comment by xtaci** [comment]
there are several computations in kcptun:
1.  encryption/decryption
2. erasure coding/decoding
3. package reordering

stunnel is much simpler.

**Comment by PtDragon** [comment]
Can packet reordering be bottleneck?
As encryption does no t affect speed, erasure coding should be extremely fast according to tests and reordering i can't test separately.

**Comment by xtaci** [comment]
possibly, cause packet reordering introduces data splitting, merging, reordering which is basically 'memory hard'.

**Comment by PtDragon** [comment]
Any way to optimize reordering so it will eat less CPU?

**Comment by xtaci** [comment]
https://en.wikipedia.org/wiki/Large_send_offload
it's usually done in NIC chips.

**Comment by PtDragon** [comment]
Yeah, but here we have software that does reordering at software level so there can be a way to optimize it at software level, right?

**Comment by xtaci** [comment]
only if you can find a better data structure than current one. 
after all , it's an open & interesting topic, you could look into the struct KCP, and should find  something like snd_queue .

**Comment by PtDragon** [comment]
Thanks, I will try to look at it and will try find something better!
P.S. Can you please look at new bug 532 i dicovered?

**Comment by xxxman2008** [comment]
@PtDragon  As you say "Same VPS easily handles over gigabit of stunnel traffic".  I really interesting how do you get the result?  Can you talk about it?   

TSO、UFO、GSO、LRO、GRO And RSS  is always run in "real machine",  can not be done in  VPS.

If you really want to do something, OK ,the key is : 
1/   HIGH FREQ  CPU 
2/   NOT encryption/decryption the packets.  Enc/decry  eat most of your cpu . that's why  intel add "native AES " function on new CPU.  

Raymond

**Comment by PtDragon** [comment]
@xxxman2008 Sure, i can talk about it ;)
I have several VPS aroud the world. Not usual ones that can handle just 100mbit and have low CPU power but those that can handle 1-10gbit of traffic and most of them designed for DDoS defence. 
For stunnel encryption goes via AES-NI so at around 90Mbyte/sec download CPU stays below 20% average. (for example of AES-NI speed my home machine  CPU i7-3770@4.3 can encrypt up to 3500Mbyte/sec)
1) 3.4Ghz, 2 cores, 99% working only for me.
2) In this case enabling or disabling encryption/decription does not really matter as there is AES-NI support.
